config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'user',
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               omniauth_callbacks: "users/omniauth_callbacks"
             }
  devise_scope :user do
    #get  'user/profile', to: 'users/registrations#profile', as: :user_profile
    #patch 'user/profile', to: 'users/registrations#update_profile'
    #post 'user/destroy_attachment', to: 'users/registrations#destroy_attachment', as: :user_destroy_attachment
    #post "/subscribe" => "users/registrations#subscribe", :as => :getKey
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: 'graduate_project#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'users/sessions#new'
    end
  end

  namespace :admin do
    resources :projects do
      collection do
        get :autocomplete
      end
    end
    resources :customers do
      collection do
        get :autocomplete
      end
    end
    resources :investors
    resources :constructors
    resources :developments
    resources :operators
    resources :users
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  include AASM
  include CustomerSearch
  # Associations
  belongs_to :city, class_name: 'RegionData', foreign_key: :city_id, optional: true
  has_many :notes, as: :objectable, dependent: :destroy
  accepts_nested_attributes_for :notes, allow_destroy: true

  # Validations
  validates :name, presence: true, format: { with: /\s/ }
  # validates :phone_number, presence: true, uniqueness: true, format: { with: /\A([+]\w|)+[0-9]*$\z/ }
  validates :phone_number, presence: true, format: { with: /\A([+]\w|)+[0-9]*$\z/ }
  #, unless: -> { User.current.marketing? || User.current.super_admin?
  validates :email, allow_blank: true, format: { with: /\A^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$\z/ }
  validates :identity_card, allow_blank: true, format: { with: /\A^(?=[A-Z0-9]*$)(?:.{9}|.{12})$\z/ }

  # AASM
  aasm column: :state, whiny_transitions: false do
    state :inauthentic, initial: true   # Chưa xác thực
    state :phone_authentic              # Xác thực số điện thoại
    state :authentic                    # Xác thực đầy đủ
  end

  scope :by_ids, -> (ids) { where id: ids }

  def get_gender
    Constant::CUSTOMER_GENDER.invert.key(gender)
  end

  def get_dob
    dob.present? ? dob.strftime('%d/%m/%Y') : ''
  end

  def name_and_phone
    "#{name} - #{phone_number}"
  end

  def get_state
    I18n.t("customer.states.#{self.aasm.current_state}")
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < GraduateProjectController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /admin/customers
  # GET /admin/customers.json
  def index
    #authorize :customer, :index?
    #@customers = policy_scope(Customer)
    query = params[:query].presence || "*"
    @customers = Customer.all
    @pagy, @customers = pagy(@customers.search_result(query), items: Settings.admin.pagination.customer.per_page)
  end

  def autocomplete
    #@customers = policy_scope(Customer)
    render json: @customers.autocomplete_result(params[:query])
  end

  # GET /admin/customers/1
  # GET /admin/customers/1.json
  def show
  end

  # GET /admin/customers/new
  def new
    @customer = Customer.new
    @cities = RegionData.cities.pluck(:name_with_type, :id)
  end

  # GET /admin/customers/1/edit
  def edit
    #@is_disabled = !policy(@customer).update?
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    @customer_notes = @customer.notes
  end

  # POST /admin/customers
  # POST /admin/customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.created_by_id = current_user.id
    #if params[:form_id] == 'quick_create'
    #  authorize @customer
    #  respond_to do |format|
    #    @customer.save if @customer.valid?
    #    format.js { render :new }
    #  end
    #  return
    #end
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to edit_admin_customer_path(@customer.id), notice: 'Khách hàng đã được tạo thành công.' }
        format.json { render :edit, status: :created, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    #if params[:save_visit_journey] || params[:save_form_journey]
    #  respond_to do |format|
    #    @customer.assign_attributes(customer_params)
    #    @customer.save if @customer.valid?
    #    format.js { render :edit }
    #  end
    #elsif params[:cancel]
    #  respond_to do |format|
    #    format.js { render :edit }
    #  end
    #else
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to edit_admin_customer_path(@customer.id), notice: 'Khách hàng đã được chỉnh sửa thành công.' }
        format.json { render :edit, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/customers/1
  # DELETE /admin/customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: 'Xóa thành công.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
    @is_disabled = false
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:name, :phone_number, :second_phone_number, :gender, :email, :identity_card, :city_id, :address, :dob,
                                     :data_source, :country_code, { :customer_characteristic => [] }, :facebook_uid, :job, :property_ownership, :nationality, :financial_capability,
                                     :detail, :income, :position, :work_place, :marital_status, notes_attributes: [:id, :created_by_id, :content, :_destroy],
                                     visit_journeys_attributes: [:id, :title, :visited_link, :visited_date, :visit_id, :_destroy],
                                     form_journeys_attributes: [:id, :recent_conversion, :first_name, :last_name, :phone_number, :email, :recent_conversion_date, :_destroy])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.haml
.row
  .col
    = form_with model: [:admin, @customer], local: true, class: 'form-customer' do |f|
      - unless @is_disabled
        .row
          .col
            .card.mb-3
              .card-body
                .float-right
                  %button.btn.btn-danger.button-save= @customer.new_record? ? 'Lưu' : 'Lưu thay đổi'
      .card
        .card-body
          .row
            .col
              .card.shadow.mb-4
                %a.d-block.card-header.py-3{"aria-controls" => "collapseCardExample", "aria-expanded" => "true", "data-toggle" => "collapse", :href => "#collapseCardExample", :role => "button"}
                  %h5.m-0.font-weight-bold.text-primary Thông tin khách hàng
                #collapseCardExample.collapse.show
                  .card-body
                    .gp-field-group
                      .gp-field-group-body
                        .row
                          .col
                            .form-group
                              = f.label :name, 'Tên khách hàng'
                              = f.text_field :name, class: 'form-control', disabled: @is_disabled
                              - f.object.errors.messages[:name].each do |name_error|
                                %span.invalid-feedback.custom-validation= name_error
                            .form-group
                              = f.label :phone_number, 'Số điện thoại'
                              = f.text_field :phone_number, class: 'form-control', disabled: @is_disabled
                              - f.object.errors.messages[:phone_number].each do |phone_number_error|
                                %span.invalid-feedback.custom-validation= phone_number_error
                            .form-group
                              = f.label :second_phone_number, 'Số điện thoại phụ'
                              = f.text_field :second_phone_number, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :gender, 'Giới tính'
                              = f.select :gender, options_for_select(Constant::CUSTOMER_GENDER.invert, @customer.gender), {include_blank: true}, {class: 'form-control gp-select2', disabled: @is_disabled}
                            .form-group
                              = f.label :email, 'Email'
                              = f.text_field :email, class: 'form-control', disabled: @is_disabled
                              - f.object.errors.messages[:email].each do |email_error|
                                %span.invalid-feedback.custom-validation= email_error
                            .form-group
                              = f.label :identity_card, 'CMND'
                              = f.text_field :identity_card, class: 'form-control', disabled: @is_disabled
                              - f.object.errors.messages[:identity_card].each do |identity_card_error|
                                %span.invalid-feedback.custom-validation= identity_card_error
                            .form-group
                              = f.label :city_id, 'Tỉnh/Thành phố'
                              = f.select :city_id, options_for_select(@cities, f.object.city_id), {include_blank: true}, {class: 'form-control gp-select2', disabled: @is_disabled}
                            .form-group
                              = f.label :address, 'Địa chỉ'
                              = f.text_area :address, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :dob, 'Ngày sinh'
                              .input-group
                                .input-group-prepend
                                  %span.input-group-text
                                    %i.far.fa-calendar-alt
                                = f.text_field :dob, class: 'form-control float-right datepicker', value: f.object.get_dob, disabled: @is_disabled
                            .form-group
                              = f.label :data_source, 'Nguồn dữ liệu'
                              = f.select :data_source, options_for_select(Constant::CUSTOMER_DATA_SOURCE.invert, @customer.data_source), {include_blank: true}, {class: 'form-control gp-select2', disabled: @is_disabled}
                            .form-group
                              = f.label :customer_characteristic, 'Đặc tính khách hàng'
                              = f.select :customer_characteristic, options_for_select(Constant::CUSTOMER_CUSTOMER_CHARACTERISTIC.invert, @customer.customer_characteristic), {include_hidden: false}, {class: 'form-control gp-select2', multiple: true, disabled: @is_disabled}
                            .form-group
                              = f.label :state, 'Trạng thái xác thực'
                              = f.text_field :state, class: 'form-control', disabled: true, value: f.object.get_state
            .col
              .card.shadow.mb-4
                %a.d-block.card-header.py-3{"aria-controls" => "collapseCardExample1", "aria-expanded" => "true", "data-toggle" => "collapse", :href => "#collapseCardExample1", :role => "button"}
                  %h5.m-0.font-weight-bold.text-primary Thông tin thêm
                #collapseCardExample1.collapse.show
                  .card-body
                    .gp-field-group
                      .gp-field-group-body
                        .row
                          .col
                            .form-group
                              = f.label :job, 'Nghề nghiệp'
                              = f.text_field :job, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :property_ownership, 'Tài sản sở hữu'
                              = f.text_field :property_ownership, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :nationality, 'Quốc tịch'
                              = f.text_field :nationality, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :financial_capability, 'Khả năng tài chính'
                              = f.text_field :financial_capability, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :detail, 'Mô tả thêm'
                              = f.text_area :detail, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :income, 'Thu nhập'
                              = f.text_field :income, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :position, 'Chức vụ'
                              = f.text_field :position, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :work_place, 'Nơi công tác'
                              = f.text_field :work_place, class: 'form-control', disabled: @is_disabled
                            .form-group
                              = f.label :marital_status, 'Tình trạng hôn nhân'
                              = f.select :marital_status, options_for_select(Constant::CUSTOMER_MARITAL_STATUS.invert, @customer.marital_status), {include_blank: "Vui lòng chọn"}, {class: 'form-control gp-select2', disabled: @is_disabled}
              .card.shadow.mb-4
                %a.d-block.card-header.py-3{"aria-controls" => "collapseCardExample2", "aria-expanded" => "true", "data-toggle" => "collapse", :href => "#collapseCardExample2", :role => "button"}
                  %h5.m-0.font-weight-bold.text-primary Ghi chú
                #collapseCardExample2.collapse.show
                  .card-body
                    #notes
                      = f.fields_for :notes do |note|
                        %div.note
                          = render 'note_fields', f: note
                      .links
                        = link_to_add_association f, :notes do
                          %button.btn.btn-primary{type: 'button', disabled: @is_disabled}
                            %i.fas.fa-plus
                            Thêm ghi chú

app/views/admin/customers/_note_fields.html.haml
.nested-fields
  .row
    .col-11
      .form-group
        .fields
          = f.text_area :content, class: 'form-control', disabled: @is_disabled
          = f.text_field :created_by_id, hidden: true, value: current_user.id
          - f.object.errors.messages[:content].each do |content_error|
            %span.invalid-feedback.custom-validation= content_error
          %span= f.object.author.full_name if (f.object.author.present? && f.object.errors.blank?)
          %span{style: 'font-style: oblique'}= '- Tạo lúc: ' + f.object.created_at.localtime.strftime('%d/%m/%Y %H:%M') if f.object.created_at.present?
    .col-1
      = link_to_remove_association f do
        .form-group
          %button.btn.btn-outline-danger{type: 'button', disabled: @is_disabled}
            %i.fas.fa-trash

app/views/admin/customers/edit.html.haml
- content_for :content_body do
  %h3.text-gray-800 Chỉnh sửa khách hàng
  %a.header-back{href: admin_customers_path}
    %i.fas.fa-angle-left
      Trở lại danh sách
  = render 'form'

app/views/admin/customers/index.html.haml
- content_for :content_header do
  .d-sm-flex.justify-content-between.mb-4
    .col-sm-6
      %h1.h3.mb-0.text-gray-800 Khách Hàng
- content_for :content_body do
  .row
    .col
      .card
        .card-body
          -#%form.mr-auto.my-2.my-md-0.mw-100.navbar-search
          -#  .input-group
          -#    %input.form-control.bg-light.border-0.small{"aria-describedby" => "basic-addon2", "aria-label" => "Search", :placeholder => "Search for...", :type => "text"}/
          -#    .input-group-append
          -#      %button.btn.btn-primary{:type => "button"}
          -#        %i.fas.fa-search.fa-sm
          = form_with url: admin_customers_path, method: :get, local: true, class: 'mr-auto my-2 my-md-0 mw-100 navbar-search' do |f|
            .input-group
              = f.text_field :query, value: params[:query], id: 'customer-search', class: 'form-control typeahead bg-light border-0 small', type: 'search', "aria-label" => "Search", placeholder: 'Tìm kiếm theo: Tên/SĐT'
              .input-group-append
                %button.btn.btn-primary{:type => "submit"}
                  %i.fas.fa-search.fa-sm
  .card
    .card-body
      .table-responsive.p-0
        %table.table.text-nowrap.table-hover
          %thead
            %tr
              %th Tên khách hàng
              %th Số điện thoại
              %th Số điện thoại phụ
              %th Giới tính
              %th Email
              %th CMND
              %th Ngày sinh
              %th Xác thực
              %th
          %tbody
            - @customers.each do |customer|
              %tr
                %td.align-middle= customer.name
                %td.align-middle= customer.phone_number
                %td.align-middle= customer.second_phone_number
                %td.align-middle= customer.get_gender
                %td.align-middle= customer.email
                %td.align-middle= customer.identity_card
                %td.align-middle= customer.get_dob
                %td.align-middle= customer.get_state
                %td.align-middle.text-right
                  %a.btn.btn-outline-primary.btn-edit{href: edit_admin_customer_path(customer.id)}
                    %i.fas.fa-pencil-alt
                  -#- if policy(customer).destroy?
                  %a.btn.btn-outline-primary{href: admin_customer_path(customer.id), data: {method: 'delete', confirm: 'Bạn chắc chắn muốn xóa bản ghi này?'}}
                    %i.fas.fa-trash
            .row
              .col-6
                = render partial: 'shared/pagination', locals: { pagy: @pagy }
              .col-6
                %a.btn.btn-gp-import
                  %i.fas.fa-cloud-upload-alt.mr-1
                  %span Import

- content_for :content_footer do
  %footer.main-footer.main-footer-fixed
    .row
      .col-12
        = link_to 'Tạo mới', new_admin_customer_path, class: 'btn btn-primary'

app/views/admin/customers/new.html.haml
- content_for :content_body do
  %h3.text-gray-800 Thêm mới khách hàng
  %a.header-back{href: admin_customers_path}
    %i.fas.fa-angle-left
      Trở lại danh sách
  = render 'form'

app/views/admin/customers/show.html.haml
- content_for :content_body do
  = render 'form'