config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'user',
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               omniauth_callbacks: "users/omniauth_callbacks"
             }
  devise_scope :user do
    #get  'user/profile', to: 'users/registrations#profile', as: :user_profile
    #patch 'user/profile', to: 'users/registrations#update_profile'
    #post 'user/destroy_attachment', to: 'users/registrations#destroy_attachment', as: :user_destroy_attachment
    #post "/subscribe" => "users/registrations#subscribe", :as => :getKey
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: 'graduate_project#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'users/sessions#new'
    end
  end

  namespace :admin do
    resources :projects do
      collection do
        get :autocomplete
      end
    end
    resources :customers do
      collection do
        get :autocomplete
      end
    end
    resources :investors
    resources :constructors
    resources :developments
    resources :operators
    resources :users
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include ProjectSearch
  #include ConvertSlug
  #include ActiveModel::Validations
  #
  ## Attributes Accessor
  #attr_accessor :not_required_image
  #
  ## Uploader
  #mount_uploaders :images, ProjectImageUploader
  #mount_uploader :sale_policy, ProjectUploader
  #mount_uploaders :internal_utility_images, ProjectImageUploader
  #mount_uploaders :external_utility_images, ProjectImageUploader
  #mount_uploaders :design_style_images, ProjectImageUploader

  # Callbacks
  after_commit :remove_previously_stored_sale_policy, on: :update
  after_update :update_deal_cached_at

  # Associations
  has_many :milestones, inverse_of: :project, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :layouts, dependent: :destroy
  has_many :divisions, dependent: :destroy
  accepts_nested_attributes_for :milestones, allow_destroy: true
  has_many :legal_documents, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :legal_documents, allow_destroy: true
  has_one :region, as: :objectable, dependent: :destroy
  accepts_nested_attributes_for :region, allow_destroy: true
  has_many :payment_schedules, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :payment_schedules, allow_destroy: true
  has_many :customer_tickets, as: :objectable, dependent: :destroy
  has_many :interactive_layouts, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :interactive_layouts, allow_destroy: true
  has_many :regulations
  has_many :deals
  has_many :key_values, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :key_values, allow_destroy: true
  has_many :floorplan_images, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :floorplan_images, allow_destroy: true
  has_many :documents, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :documents, allow_destroy: true

  # Validations
  validates :name, presence: true
  validates :real_estate_type, presence: true
  validates :locking_time, numericality: { allow_blank: true, only_integer: true, greater_than_or_equal_to: 0 }
  validates :construction_density, numericality: { greater_than: 0, less_than_or_equal_to: 100 }, allow_blank: true
  validates :total_area, numericality: { greater_than: 0 }, allow_blank: true
  validates :investors, presence: true
  validates :internal_utilities, presence: true
  validates :ownership_period, presence: true
  validates :loan_percentage_support, numericality: { greater_than: 0, less_than_or_equal_to: 100 }, allow_blank: true
  validates :loan_support_period, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validates :discount_support, numericality: { greater_than: 0, less_than_or_equal_to: 100 }, allow_blank: true
  # validates :bonus, numericality: { greater_than: 0 }, allow_blank: true
  # validate :commission_validate_by_commission_type
  validates :images, presence: true, unless: -> { not_required_image.present? }
  validates :high_level_number, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validates :low_level_number, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validate :payment_schedule_validate
  validates :price_from, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1000 }, allow_blank: true
  validates :price_to, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1000 }, allow_blank: true
  validates :area_from, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :area_to, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validate :interactive_layout_validate
  #validates :link_video, :position_link_embed, valid_url: true


  scope :by_ids, -> (ids) { where id: ids }

  def update_deal_cached_at
    self.deals.update_all(cached_at: Time.now)
  end

  def commission_validate_by_commission_type
    if commission_type.to_i == 1 && commission.present?
      if commission.to_i == 0
        errors.add(:commission, 'Hoa hồng (VNĐ) phải là số.')
      elsif commission >= 100
        errors.add(:commission, 'Hoa hồng (VNĐ) không được quá 100%.')
      elsif commission < 0
        errors.add(:commission, 'Hoa hồng (VNĐ) không được nhập nhỏ hơn 0.')
      end
    end
    if commission_type.to_i == 0 && commission.present?
      if commission.to_i == 0
        errors.add(:commission, 'Hoa hồng (VNĐ) phải là số.')
      elsif commission < 0
        errors.add(:commission, 'Hoa hồng (VNĐ) không được nhập nhỏ hơn 0.')
      end
    end
    if commission_type.blank? && commission.present?
      errors.add(:commission_type, 'Vui lòng chọn hình thức tính phí của dự án.')
    end
  end

  def min_price
    products.minimum(:sum_price) || price_from ? price_from.to_f * 1000000000 : nil
  end

  def max_price
    products.maximum(:sum_price) || price_to ? price_to.to_f * 1000000000 : nil
  end

  def min_price_filter
    products.present? ? products.minimum(:sum_price) : price_from.to_f * 1000000000
  end

  def max_price_filter
    products.present? ? products.maximum(:sum_price) : price_to.to_f * 1000000000
  end

  def min_acreage
    [products.minimum(:carpet_area), products.minimum(:plot_area)].compact.min || area_from
  end

  def max_acreage
    [products.maximum(:carpet_area), products.maximum(:plot_area)].compact.max || area_to
  end

  def min_acreage_filter
    [products.minimum(:carpet_area), products.minimum(:plot_area)].compact.min || area_from.to_f
  end

  def max_acreage_filter
    [products.maximum(:carpet_area), products.maximum(:plot_area)].compact.max || area_to.to_f
  end

  def furnitures
    products&.map(&:furniture).compact.uniq
  end

  def online_transaction
    products.present?
  end

  def investors_name
    Investor.where(id: investors).map(&:name)
  end

  def real_estate_type_name
    real_estate_type&.map { |t| Constant::PROJECT_REAL_ESTATE_TYPE[t] }
  end

  def full_address
    "#{region.city&.name} #{region.district&.name} #{region.ward&.name}"
  end

  def currencies
    products&.map(&:currency).compact.uniq.map { |c| Reti::Product::CURRENCIES[c] }
  end

  def payment_schedule_validate
    high_payment_schedules = payment_schedules.reject { |p| p._destroy || p.label_schedule != 0 }
    low_payment_schedules = payment_schedules.reject { |p| p._destroy || p.label_schedule != 1 }
    high = high_payment_schedules.size
    low = low_payment_schedules.size
    value_high = high_payment_schedules.map(&:pay).sum()
    value_low = low_payment_schedules.map(&:pay).sum()
    # check khoi cao tang
    errors.add(:high_level_number, :equal_to_payment_schedule) unless high == high_level_number.to_i
    errors.add(:high_level_number, :equal_to_value_payment_schedule) if high_level_number.to_i > 0 && high > 0 && value_high != 100
    # check khoi thap tang
    errors.add(:low_level_number, :equal_to_payment_schedule) unless low == low_level_number.to_i
    errors.add(:low_level_number, :equal_to_value_payment_schedule) if low_level_number.to_i > 0 && low > 0 && value_low != 100
  end

  def interactive_layout_validate
    errors.add(:divis, "Bạn đang nhập 1 mặt bằng 2 lần") if interactive_layouts.map(&:division_id).uniq.size != interactive_layouts.map(&:division_id).size
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < GraduateProjectController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    query = params[:query].presence || "*"
    @projects = Project.all
    @pagy, @projects = pagy(@projects.search_result(query), items: Settings.admin.pagination.customer.per_page)
  end

  def autocomplete
    render json: @projects.autocomplete_result(params[:query])
  end


  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
  end

  # GET /admin/projects/new
  def new
    @project = Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(admin_project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update(admin_project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.fetch(:admin_project, {})
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_form.html.haml
= form_for @admin_project do |f|
  - if @admin_project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_project.errors.count, "error")} prohibited this admin_project from being saved:"
      %ul
        - @admin_project.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/admin/projects/edit.html.haml
%h1 Editing admin_project

= render 'form'

= link_to 'Show', @admin_project
\|
= link_to 'Back', admin_projects_path

app/views/admin/projects/index.html.haml
- content_for :content_header do
  .d-sm-flex.justify-content-between.mb-4
    .col-sm-6
      %h1.h3.mb-0.text-gray-800 Dự án
- content_for :content_body do
  .row
    .col
      .card
        .card-body
          %form.mr-auto.my-2.my-md-0.mw-100.navbar-search
            .input-group
              = form_with url: admin_projects_path, method: :get, local: true, class: 'input-group search-group' do |f|
                = f.text_field :query, value: params[:query], id: 'customer-search', class: 'form-control bg-light border-0 small', type: 'search', placeholder: 'Tìm kiếm...'
                .input-group-append1
                  %button.btn.btn-primary{type: 'submit', style: 'height: 38px !important'}
                    %i.fa.fa-search.fa-sm
  .card
    .card-body
      .table-responsive.p-0
        %table.table.text-nowrap.table-hover
          %thead
            %tr
              %th.first-col-stick Hình ảnh
              -#%th.second-col-stick Mã dự án
              %th.second-col-stick Tên dự án
              %th Loại hình
              %th Vị trí
              %th Giá từ
              %th Giá đến
              %th Diện tích nhỏ nhất
              %th Diện tích lớn nhất
              %th Số hàng còn
              %th.last-col-stick
          %tbody
            - @projects.each do |project|
              %tr
                %td.align-middle.first-col-stick= image_tag(project.images.first.url, class: 'img-thumbnail', style: 'width: 100px') if project.images.first.present?
                -#%td.align-middle.second-col-stick= "DA-#{project.id}"
                %td.align-middle.second-col-stick= project.name
                %td.align-middle= project.real_estate_type_name.join(', ')
                %td.align-middle= project.region&.city&.name
                %td.align-middle= currency(project.min_price)
                %td.align-middle= currency(project.max_price)
                %td.align-middle= acreage(project.min_acreage)
                %td.align-middle= acreage(project.max_acreage)
                %td.align-middle= ''
                %td.align-middle.text-right.last-col-stick
                  %a.btn.btn-outline-primary.btn-edit{href: edit_admin_project_path(project)}
                    %i.fas.fa-pencil-alt
                  -#- if policy(project).destroy?
                  %a.btn.btn-outline-primary{href: admin_project_path(project.id), data: {method: 'delete', confirm: 'Bạn chắc chắn muốn xóa bản ghi này?'}}
                    %i.fas.fa-trash
            .row
              .col-6
                = render partial: 'shared/pagination', locals: { pagy: @pagy }
              .col-6
                %a.btn.btn-gp-import
                  %i.fas.fa-upload.mr-2
                  Import

- content_for :content_footer do
  %footer.main-footer.main-footer-fixed
    .row
      .col-12
        = link_to 'Tạo mới', new_admin_project_path, class: 'btn btn-primary'

app/views/admin/projects/new.html.haml
%h1 New admin_project

= render 'form'

= link_to 'Back', admin_projects_path

app/views/admin/projects/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_admin_project_path(@admin_project)
\|
= link_to 'Back', admin_projects_path